# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcsg324-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Craft/Vivado/alu/alu.cache/wt [current_project]
set_property parent.project_path D:/Craft/Vivado/alu/alu.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Craft/Vivado/alu/alu.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib D:/Craft/Vivado/alu/alu.srcs/sources_1/new/alu.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Craft/Vivado/alu/alu.srcs/constrs_2/new/cons.xdc
set_property used_in_implementation false [get_files D:/Craft/Vivado/alu/alu.srcs/constrs_2/new/cons.xdc]


synth_design -top alu -part xc7a35tcsg324-2


write_checkpoint -force -noxdef alu.dcp

catch { report_utilization -file alu_utilization_synth.rpt -pb alu_utilization_synth.pb }
